import Head from "next/head";
import { useEffect, useState } from "react";
import Navbar from "@/components/Navbar/Navbar";
import styles from "@/styles/Home.module.css";
import AppSection from "@/components/App/AppSection";
import { AppWithDevelopersProps } from "../components/types";
import axios from "axios";
import debounce from "lodash/debounce";
import Footer from "@/components/Footer/Footer";

export default function Home() {
  const [webAppsRandom, setWebAppsRandom] = useState<AppWithDevelopersProps[]>(
    []
  );
  const [mobileAppsRandom, setMobileAppsRandom] = useState<
    AppWithDevelopersProps[]
  >([]);
  const [nativeAppsRandom, setNativeAppsRandom] = useState<
    AppWithDevelopersProps[]
  >([]);
  const [isLoading, setIsLoading] = useState(true);

  const app_url = `${process.env.NEXT_PUBLIC_APP_URL}`;

  const getRandomApps = (appsList: any, maxApps: number) => {
    if (appsList.length <= maxApps) return appsList;

    const shuffled = appsList.sort(() => 0.5 - Math.random());
    return shuffled.slice(0, maxApps);
  };
  useEffect(() => {
    const fetchData = async () => {
      setIsLoading(true);
      try {
        const res = await axios.get(app_url);
        const allApps: AppWithDevelopersProps[] = res.data.apps;

        if (allApps.length > 0) {
          const webApps = allApps.filter((app) => app.type === "Web");
          const mobileApps = allApps.filter((app) => app.type === "Mobile");
          const nativeApps = allApps.filter((app) => app.type === "Native");

          let webAppsList;
          let mobileAppsList;
          let nativeAppsList;

          // Checking the screen size based on window.innerWidth
          if (window.innerWidth <= 500) {
            webAppsList = getRandomApps(webApps, 1);
            mobileAppsList = getRandomApps(mobileApps, 1);
            nativeAppsList = getRandomApps(nativeApps, 1);
          } else if (window.innerWidth <= 700) {
            webAppsList = getRandomApps(webApps, 2);
            mobileAppsList = getRandomApps(mobileApps, 2);
            nativeAppsList = getRandomApps(nativeApps, 2);
          } else if (window.innerWidth <= 900) {
            webAppsList = getRandomApps(webApps, 3);
            mobileAppsList = getRandomApps(mobileApps, 3);
            nativeAppsList = getRandomApps(nativeApps, 3);
          } else if (window.innerWidth <= 1200) {
            webAppsList = getRandomApps(webApps, 4);
            mobileAppsList = getRandomApps(mobileApps, 4);
            nativeAppsList = getRandomApps(nativeApps, 4);
          } else {
            webAppsList = getRandomApps(webApps, 5);
            mobileAppsList = getRandomApps(mobileApps, 5);
            nativeAppsList = getRandomApps(nativeApps, 5);
          }

          setWebAppsRandom(webAppsList);
          setMobileAppsRandom(mobileAppsList);
          setNativeAppsRandom(nativeAppsList);
        }
      } catch (error) {
        console.error(error);
      } finally {
        setIsLoading(false);
      }
    };
    const debouncedFetchData = debounce(fetchData, 300);

    debouncedFetchData(); // Use the debounced version of fetchData

    // Event listener to recheck screen size when the window is resized
    window.addEventListener("resize", debouncedFetchData);

    // Cleanup the event listener when the component unmounts
    return () => {
      window.removeEventListener("resize", debouncedFetchData);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Adies Capstones Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/AdieLogo.png" />{" "}
      </Head>
      <main className={styles.main}>
        <Navbar />
        {isLoading && (
          <div className={styles.loadingSpinnerWrapper}>
            <div className={styles.loadingSpinner}>
              <div>
                <div
                  role="status"
                  className="absolute -translate-x-1/2 -translate-y-1/2 top-2/4 left-1/2"
                >
                  <svg
                    aria-hidden="true"
                    className="w-8 h-8 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600"
                    viewBox="0 0 100 101"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z"
                      fill="currentColor"
                    />
                    <path
                      d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z"
                      fill="green"
                    />
                  </svg>
                </div>
              </div>
              <div>
                <h2>Loading...</h2>
              </div>
            </div>
          </div>
        )}
        <section className={styles.appsWrapper}>
          {!isLoading && (
            <>
              <AppSection
                sectionTitle="Web apps"
                apps={webAppsRandom}
                seeAllLink={`/see-more?type=web`}
              />
              <AppSection
                sectionTitle="Mobile apps"
                apps={mobileAppsRandom}
                seeAllLink={`/see-more?type=mobile`}
              />
              <AppSection
                sectionTitle="Native apps"
                apps={nativeAppsRandom}
                seeAllLink={`/see-more?type=native`}
              />
            </>
          )}
        </section>
      </main>
      <Footer />
    </>
  );
}
